---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  
  - name: install apache2 php library
    apt:
       name: libapache2-mod-php
       state: latest
