---

- hosts: web_servers
  become: true
  tasks:
    
    - name: copy default html file for site
      tags: apache. apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


    - name: install apache2
      tags: apache2,ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: install nikto
      tags: nikto
      apt:
        name: nikto
    
